"""created table ReviewerPullRequestAssignment

Revision ID: 30cccf3bdeb7
Revises: 8db539add7a1
Create Date: 2025-11-16 12:02:25.147404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30cccf3bdeb7'
down_revision: Union[str, Sequence[str], None] = '8db539add7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_pull_request_assignment',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pr_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['pull_request.id'], name='reviewer_pr_assignment_pr_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='reviewer_pr_assignment_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'pr_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviewer_pull_request_assignment')
    # ### end Alembic commands ###
